### ISSUE TITLE
Evaluation Code and Pretrained Weights

### ISSUE THREAD

**Issue by ldkong1205** [NeurAI-Lab/G2S#1]
Hi @hemangchawla, I would like to ask whether or not you have a plan to release the evaluation code and pretrained models for reproduction. Thanks!

**Comment by hemangchawla** [comment]
Hi @ldkong1205 , apologies for the late response. Unfortunately, we couldn't share the complete code earlier as it is proprietary. You may use code from this repo instead: https://github.com/ArnavVarma/G2S
